### ISSUE TITLE
Fix DNF components

### ISSUE THREAD

**Issue by PatrickBaus** [TU-Darmstadt-APQ/Laser_Backplane_DVI#1]
There are quite a few components incorrectly marked as DNF. Fix these.

See: https://github.com/TU-Darmstadt-APQ/Laser_Backplane_DVI/releases/download/v1.7.3/schematics_1.7_default.pdf

**Comment by tpreuschoff** [comment]
Added two variants: 'default' without current modulation circuit and 'curr_mod'
